clone_folder: C:\dev\workspace\MotionBox

environment:
  matrix:
    - qt: qt5
      platform: linux

image: ubuntu1804

install:
  - cd ..
  - cmd: appveyor DownloadFile http://omega.gg/get/Sky/3rdparty/%platform% -FileName 3rdparty.zip
  - cmd: 7z x 3rdparty.zip
  - git clone https://github.com/omega-gg/Sky
  - sh: cd Sky
  - sh: sh 3rdparty.sh all %qt% ubuntu
  - sh: cd ..
  - cd MotionBox
  - sh configure.sh %qt% %platform%

build_script:
  - cd ../Sky
  - sh build.sh %qt% %platform% tools
  - cd ../MotionBox
  - sh build.sh %qt% %platform% deploy
  - cd deploy
  - rm .gitignore
  - 7z a ../MotionBox-%qt%-%platform%.zip *

artifacts:
  - path: MotionBox-%qt%-%platform%.zip
