clone_folder: C:\dev\workspace\MotionBox

environment:
  matrix:
    - qt: qt4
      platform: win32

    - qt: qt5
      platform: win32

    - qt: qt5
      platform: win64

install:
  - cd MotionBox
  - sh 3rdparty.sh %platform%
  - sh configure.sh %qt% %platform%

build_script:
  - cd ../Sky
  - sh build.sh %qt% %platform% tools
  - cd ../MotionBox
  - sh build.sh %qt% %platform% deploy
  - cd deploy
  - rm .gitignore
  - 7z a ../MotionBox-%platform%-%qt%.zip *

artifacts:
  - path: MotionBox-%platform%-%qt%.zip
