clone_folder: C:\dev\workspace\MotionBox

environment:
  matrix:
    - qt: qt4
      platform: win32

    - qt: qt5
      platform: win32

    - qt: qt5
      platform: win64

    - qt: qt5
      platform: win32-msvc

    - qt: qt5
      platform: win64-msvc

install:
  - sh environment.sh %qt%

build_script:
  - sh build.sh %platform% all
  - cd deploy
  - rm .gitignore
  - 7z a ../MotionBox-%platform%-%qt%.zip *

artifacts:
  - path: MotionBox-%platform%-%qt%.zip
