clone_folder: c:\dev\workspace\MotionBox

environment:
  matrix:
    - qt: qt4
      platform: win32

    - qt: qt5
      platform: win64

install:
  - cd ..
  - appveyor DownloadFile http://omega.gg/get/Sky/3rdparty/%platform% -FileName 3rdparty.zip
  - 7z x 3rdparty.zip
  - git clone https://github.com/omega-gg/Sky
  - cd Sky
  - sh configure.sh %qt% %platform%
  - cd ../MotionBox
  - sh configure.sh %qt% %platform%

build_script:
  - cd ../Sky
  - sh build.sh %qt% %platform% deploy
  - cd ../MotionBox
  - sh build.sh %qt% %platform% deploy
