clone_folder: C:\dev\workspace\MotionBox

environment:
  matrix:
    - qt: qt4
      platform: win32
      compiler: mingw

    - qt: qt5
      platform: win32
      compiler: mingw

    - qt: qt5
      platform: win64
      compiler: mingw

    - qt: qt5
      platform: win32
      compiler: msvc

    - qt: qt5
      platform: win64
      compiler: msvc

build_script:
  - sh environment.sh %compiler% %qt%
  - sh build.sh %platform% all
  - cd deploy
  - rm .gitignore
  - 7z a ../MotionBox-%platform%-%qt%.zip *

artifacts:
  - path: MotionBox-%platform%-%qt%.zip
