#--------------------------------------------------------------------------------------------------
# Windows
#--------------------------------------------------------------------------------------------------

jobs:
- job: win32_qt5
  pool:
    vmImage: "windows-latest"
  steps:
  - bash: |
      sh build.sh win32 all
      cd deploy
      7z a ../MotionBox.zip *
  - publish: $(System.DefaultWorkingDirectory)/MotionBox.zip
    artifact: MotionBox-win32-qt5

#--------------------------------------------------------------------------------------------------

- job: win64_qt5
  pool:
    vmImage: "windows-latest"
  steps:
  - bash: |
      sh build.sh win64 all
      cd deploy
      7z a ../MotionBox.zip *
  - publish: $(System.DefaultWorkingDirectory)/MotionBox.zip
    artifact: MotionBox-win64-qt5

#--------------------------------------------------------------------------------------------------
# macOS
#--------------------------------------------------------------------------------------------------

- job: macOS_qt5
  pool:
    vmImage: "macOS-latest"
  steps:
  - bash: |
      sh build.sh macOS all
      cd deploy
      zip -rq ../MotionBox.zip *
  - publish: $(System.DefaultWorkingDirectory)/MotionBox.zip
    artifact: MotionBox-macOS-qt5

#--------------------------------------------------------------------------------------------------
# Linux
#--------------------------------------------------------------------------------------------------

- job: linux32_qt5
  pool:
    vmImage: "ubuntu-latest"
  steps:
  - bash: |
      docker run -d --name ubuntu -v $PWD:/MotionBox i386/ubuntu:18.04 tail -f /dev/null
      docker exec -t ubuntu bash -c "cd /MotionBox;
                                     apt-get update;
                                     apt-get -y install sudo curl zip git;
                                     sh build.sh linux all;
                                     cd deploy;
                                     zip -rq ../MotionBox.zip *"
  - publish: $(System.DefaultWorkingDirectory)/MotionBox.zip
    artifact: MotionBox-linux32-qt5

#--------------------------------------------------------------------------------------------------

- job: linux64_qt5
  pool:
    vmImage: "ubuntu-latest"
  steps:
  - bash: |
      docker run -d --name ubuntu -v $PWD:/MotionBox amd64/ubuntu:18.04 tail -f /dev/null
      docker exec -t ubuntu bash -c "cd /MotionBox;
                                     apt-get update;
                                     apt-get -y install sudo curl zip git;
                                     sh build.sh linux all;
                                     cd deploy;
                                     zip -rq ../MotionBox.zip *"
  - publish: $(System.DefaultWorkingDirectory)/MotionBox.zip
    artifact: MotionBox-linux64-qt5

#--------------------------------------------------------------------------------------------------
# Android
#--------------------------------------------------------------------------------------------------

- job: android_qt5
  pool:
    vmImage: "ubuntu-latest"
  steps:
  - bash: |
      docker run -d --name ubuntu -v $PWD:/MotionBox amd64/ubuntu:18.04 tail -f /dev/null
      docker exec -t ubuntu bash -c "cd /MotionBox;
                                     apt-get update;
                                     apt-get -y install sudo curl zip unzip git;
                                     sh 3rdparty.sh linux;
                                     sh build.sh android all;
                                     cd deploy;
                                     zip -rq ../MotionBox.zip *"
  - publish: $(System.DefaultWorkingDirectory)/MotionBox.zip
    artifact: MotionBox-android-qt5
