#--------------------------------------------------------------------------------------------------
# Windows
#--------------------------------------------------------------------------------------------------

jobs:
- job: win32_qt4
  pool:
    vmImage: "windows-latest"
  steps:
  - bash: |
      cd ..
      curl -L -o 3rdparty.zip http://omega.gg/get/Sky/3rdparty/win32
      unzip 3rdparty.zip
      git clone https://github.com/omega-gg/Sky
      cd s
      sh configure.sh qt4 win32
      cd ../Sky
      sh build.sh qt4 win32 tools
      cd ../s
      sh build.sh qt4 win32 deploy
  - publish: $(System.DefaultWorkingDirectory)/deploy
    artifact: MotionBox-win32-qt4
